<?php

namespace common\models;

use common\components\helpers\CustomDateHelper;
use Yii;
use yii\helpers\Json;
/**
 * This is the model class for table "{{%bonus_scheme_records_history}}".
 *
 * @property integer $id
 * @property integer $scheme_id
 * @property string $params
 * @property string $update_date
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $deduct_lp
 *
 * @property BonusScheme $scheme
 */
class BonusSchemeRecordsHistory extends AbstractActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%bonus_scheme_records_history}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['scheme_id'], 'required'],
            [['scheme_id', 'created_at', 'updated_at'], 'integer'],
            [['params','deduct_lp'], 'string'],
            [['update_date'], 'safe'],
            [['scheme_id'], 'exist', 'skipOnError' => true, 'targetClass' => BonusScheme::className(), 'targetAttribute' => ['scheme_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app/users', 'ID'),
            'scheme_id' => Yii::t('app/users', 'Scheme ID'),
            'params' => Yii::t('app/users', 'Params'),
            'update_date' => Yii::t('app/users', 'Update Date'),
            'created_at' => Yii::t('app/users', 'Created At'),
            'updated_at' => Yii::t('app/users', 'Updated At'),
            'deduct_lp' => Yii::t('app/users','Deduct tax at legal person'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getScheme()
    {
        return $this->hasOne(BonusScheme::className(), ['id' => 'scheme_id']);
    }

    /**
     * Получаем параметры на указзаную дату
     * @param $iSchemeId
     * @param $date
     * @return mixed
     */
    public static function getCurrentParamForDate($iSchemeId,$date)
    {
        if(CustomDateHelper::isCurrentMonth($date))
        {
            return BonusSchemeRecords::find()->where(['scheme_id' => $iSchemeId])->one();
        }else{
            $obParams = self::find()
                ->where(['scheme_id' => $iSchemeId])
                ->andWhere(['<=','update_date',date('Y-m-d')])
                ->one();
            if(!$obParams)
            {
                $obParams = BonusSchemeRecords::find()->where(['scheme_id' => $iSchemeId])->one();
            }
            return $obParams;
        }
    }

    /**
     * @param $arSchemesIds
     * @param $date
     * @return mixed
     */
    public static function getParamsForFewSchemes($arSchemesIds,$date)
    {
        $arSchemesIds = array_unique($arSchemesIds);
        if(CustomDateHelper::isCurrentMonth($date))
        {
            return BonusSchemeRecords::find()->where(['scheme_id' => $arSchemesIds])->indexBy('scheme_id')->all();
        }else{
            $obParams = self::find()
                ->where(['scheme_id' => $arSchemesIds])
                ->andWhere(['<=','update_date',date('Y-m-d')])
                ->indexBy('scheme_id')
                ->one();
            if(!$obParams)
            {
                $obParams = BonusSchemeRecords::find()->where(['scheme_id' => $arSchemesIds])->indexBy('scheme_id')->all();
            }
            return $obParams;
        }

    }

    /**
     * @return bool
     */
    public function beforeValidate()
    {
        if(is_array($this->params))
            $this->params = Json::encode($this->params);
        if(is_array($this->deduct_lp))
            $this->deduct_lp = Json::encode($this->deduct_lp);
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if(is_array($this->params))
            $this->params = Json::encode($this->params);
        if(is_array($this->deduct_lp))
            $this->deduct_lp = Json::encode($this->deduct_lp);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    public function afterFind()
    {
        if(!empty($this->params))
            $this->params = Json::decode($this->params);
        if(!empty($this->deduct_lp))
            $this->deduct_lp = Json::decode($this->deduct_lp);
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
